 const famosos = [
  { nombre: "Alex Pelao", foto: "img/alex_pelao.jpg" },
  { nombre: "Marcos Da Costa", foto: "img/marcosdacosta.jpg" },
  { nombre: "The La Planta", foto: "img/thelaplanta.jpg" },
  { nombre: "El Zaraza", foto: "img/zaraza.jpg" },  
  { nombre: "Momi Giardina", foto: "img/momi.jpg" },
  { nombre: "Marito Baracus", foto: "img/marito_baracus.jpg" },
  { nombre: "Chano", foto: "img/chano.jpg" },
  { nombre: "El Tano Pasman", foto: "img/tanopasman.jpg" },
  { nombre: "Santi Maratea", foto: "img/santimaratea.jpg" },
  { nombre: "Santiago del Moro", foto: "img/delmoro.jpg" },
  { nombre: "Rafa Cotelo", foto: "img/cotelo.jpg" },
  { nombre: "Sebastián Abreu", foto: "img/abreu.jpg" },
  { nombre: "Diego Lugano", foto: "img/lugano.jpg" },
  { nombre: "Peso Pluma", foto: "img/pesopluma.jpg" },
  { nombre: "Eladio Carrión", foto: "img/eladio.jpg" },
  { nombre: "Myke Towers", foto: "img/myketowers.jpg" },
  { nombre: "Mauro Icardi", foto: "img/mauro_icardi.jpg" },
  { nombre: "Nicolás de la Cruz", foto: "img/nicolas_de_la_cruz.jpg" },
  { nombre: "Luis Suárez", foto: "img/luis_suarez.jpg" },
  { nombre: "Lionel Messi", foto: "img/lionel_messi.jpg" },
  { nombre: "Diego Forlán", foto: "img/diego_forlan.jpg" },
  { nombre: "Cristiano Ronaldo", foto: "img/cristiano_ronaldo.jpg" },
  { nombre: "Keylor Navas", foto: "img/keylor_navas.jpg" },
  { nombre: "Manuel Neuer", foto: "img/manuel_neuer.jpg" },
  { nombre: "Martín Palermo", foto: "img/martin_palermo.jpg" },
  { nombre: "Luciano Boggio", foto: "img/boggio.jpg" },
  { nombre: "Nico López", foto: "img/nico_lopez.jpg" },
  { nombre: "Gonzalo Petit", foto: "img/petit.jpg" },
  { nombre: "Eduardo Vargas", foto: "img/eduardo_vargas.jpg" },
  { nombre: "Gonzalo Carneiro", foto: "img/carneiro.jpg" },
  { nombre: "Luis Mejía", foto: "img/mejia.jpg" },
  { nombre: "Diego Maradona", foto: "img/diego_maradona.jpg" },
  { nombre: "Pelé", foto: "img/pele.jpg" },
  { nombre: "Gabriel Batistuta", foto: "img/gabriel_batistuta.jpg" },
  { nombre: "Andrés Iniesta", foto: "img/andres_iniesta.jpg" },
  { nombre: "Sergio Agüero", foto: "img/sergio_aguero.jpg" },
  { nombre: "Fernando Muslera", foto: "img/fernando_muslera.jpg" },
  { nombre: "Carlos Tévez", foto: "img/carlos_tevez.jpg" },
  { nombre: "Javier Mascherano", foto: "img/javier_mascherano.jpg" },
  { nombre: "Juan Román Riquelme", foto: "img/juan_roman_riquelme.jpg" },
  { nombre: "Fede Valverde", foto: "img/fede_valverde.jpg" },
  { nombre: "Paulo Dybala", foto: "img/paulo_dybala.jpg" },
  { nombre: "Ángel Di María", foto: "img/angel_di_maria.jpg" },
  { nombre: "Alfonso Espino", foto: "img/alfonso_espino.jpg" },
  { nombre: "Rodrigo Bentancur", foto: "img/rodrigo_bentancur.jpg" },
  { nombre: "Facundo Pellistri", foto: "img/facundo_pellistri.jpg" },
  { nombre: "Kylian Mbappé", foto: "img/kylian_mbappe.jpg" },
  { nombre: "Neymar Jr.", foto: "img/neymar_jr.jpg" },
  { nombre: "Erling Haaland", foto: "img/erling_haaland.jpg" },
  { nombre: "Robert Lewandowski", foto: "img/robert_lewandowski.jpg" },
  { nombre: "Cole Palmer", foto: "img/colepalmer.jpg" },
  { nombre: "Luka Modrić", foto: "img/luka_modric.jpg" },
  { nombre: "Toni Kroos", foto: "img/toni_kroos.jpg" },
  { nombre: "Mohamed Salah", foto: "img/mohamed_salah.jpg" },
  { nombre: "Virgil van Dijk", foto: "img/virgil_van_dijk.jpg" },
  { nombre: "Kevin De Bruyne", foto: "img/kevin_de_bruyne.jpg" },
  { nombre: "Harry Kane", foto: "img/harry_kane.jpg" },
  { nombre: "Antoine Griezmann", foto: "img/antoine_griezmann.jpg" },
  { nombre: "Gerard Piqué", foto: "img/gerard_pique.jpg" },
  { nombre: "Sergio Ramos", foto: "img/sergio_ramos.jpg" },
  { nombre: "Marcelo", foto: "img/marcelo.jpg" },
  { nombre: "Gianluigi Buffon", foto: "img/gianluigi_buffon.jpg" },
  { nombre: "Iker Casillas", foto: "img/iker_casillas.jpg" },
  { nombre: "Francesco Totti", foto: "img/francesco_totti.jpg" },
  { nombre: "Ronaldinho", foto: "img/ronaldinho.jpg" },
  { nombre: "Shakira", foto: "img/shakira.jpg" },
  { nombre: "Bad Bunny", foto: "img/bad_bunny.jpg" },
  { nombre: "María Becerra", foto: "img/maria_becerra.jpg" },
  { nombre: "Duki", foto: "img/duki.jpg" },
  { nombre: "Ricky Martin", foto: "img/ricky_martin.jpg" },
  { nombre: "Nathy Peluso", foto: "img/nathy_peluso.jpg" },
  { nombre: "Paulo Londra", foto: "img/paulo_londra.jpg" },
  { nombre: "Bizarrap", foto: "img/bizarrap.jpg" },
  { nombre: "Charly García", foto: "img/charly_garcia.jpg" },
  { nombre: "Fito Páez", foto: "img/fito_paez.jpg" },
  { nombre: "Gustavo Cerati", foto: "img/gustavo_cerati.jpg" },
  { nombre: "Alejandro Sanz", foto: "img/alejandro_sanz.jpg" },
  { nombre: "Diego Torres", foto: "img/diego_torres.jpg" },
  { nombre: "Feid", foto: "img/feid.jpg" },
  { nombre: "The Weeknd", foto: "img/the_weeknd.jpg" },
  { nombre: "Ariana Grande", foto: "img/ariana_grande.jpg" },
  { nombre: "Ed Sheeran", foto: "img/ed_sheeran.jpg" },
  { nombre: "Bruno Mars", foto: "img/bruno_mars.jpg" },
  { nombre: "Maluma", foto: "img/maluma.jpg" },
  { nombre: "Farruko", foto: "img/farruko.jpg" },
  { nombre: "Ozuna", foto: "img/ozuna.jpg" },
  { nombre: "J Balvin", foto: "img/j_balvin.jpg" },
  { nombre: "Tini Stoessel", foto: "img/tini.jpg" },
  { nombre: "Agustín Casanova", foto: "img/agustin_casanova.jpg" },
  { nombre: "Karol G", foto: "img/karol.jpg" },
  { nombre: "Natalia Oreiro", foto: "img/natalia_oreiro.jpg" },
  { nombre: "Don Omar", foto: "img/donomar.jpg" },
  { nombre: "Joaquín Sabina", foto: "img/joaquin_sabina.jpg" },
  { nombre: "Sofía Reyes", foto: "img/sofia_reyes.jpg" },
  { nombre: "Daddy Yankee", foto: "img/daddy.jpg" },
  { nombre: "Luis Fonsi", foto: "img/luis_fonsi.jpg" },
  { nombre: "Camila Cabello", foto: "img/camila_cabello.jpg" },
  { nombre: "Selena Gomez", foto: "img/selena_gomez.jpg" },
  { nombre: "Billie Eilish", foto: "img/billie_eilish.jpg" },
  { nombre: "Dua Lipa", foto: "img/dua_lipa.jpg" },
  { nombre: "Camilo", foto: "img/camilo.jpg" },
  { nombre: "Sebastián Yatra", foto: "img/sebastian_yatra.jpg" },
  { nombre: "Paulina Rubio", foto: "img/paulina_rubio.jpg" },
  { nombre: "Ricardo Montaner", foto: "img/ricardo_montaner.jpg" },
  { nombre: "Marc Anthony", foto: "img/marc_anthony.jpg" },
  { nombre: "Carlos Vives", foto: "img/carlos_vives.jpg" },
  { nombre: "Rauw Alejandro", foto: "img/rauw.jpg" },
  { nombre: "Ricardo Arjona", foto: "img/ricardo_arjona.jpg" },
  { nombre: "Juanes", foto: "img/juanes.jpg" },
  { nombre: "Quevedo", foto: "img/quevedo.jpg" },
  { nombre: "Luana", foto: "img/luana.jpg" },
  { nombre: "Luck Ra", foto: "img/luckra.jpg" },
  { nombre: "Chacho Ramos", foto: "img/chacho.jpg" },
  { nombre: "La Joaqui", foto: "img/joaqui.jpg" },
  { nombre: "Martín Piña", foto: "img/martinpiña.jpg" },
  { nombre: "Lucas Sugo", foto: "img/lucassugo.jpg" },
  { nombre: "Lali Esposito", foto: "img/lali.jpg" },
  { nombre: "Nicki Nicole", foto: "img/nicki.jpg" },
  { nombre: "Cazzu", foto: "img/cazzu.jpg" },
  { nombre: "Ruben Rada", foto: "img/rubenrada.jpg" },
  { nombre: "Leonardo DiCaprio", foto: "img/leonardo_dicaprio.jpg" },
  { nombre: "Brad Pitt", foto: "img/brad_pitt.jpg" },
  { nombre: "Tom Cruise", foto: "img/tom_cruise.jpg" },
  { nombre: "Robert De Niro", foto: "img/robert_de_niro.jpg" },
  { nombre: "Al Pacino", foto: "img/al_pacino.jpg" },
  { nombre: "Morgan Freeman", foto: "img/morgan_freeman.jpg" },
  { nombre: "Denzel Washington", foto: "img/denzel_washington.jpg" },
  { nombre: "Will Smith", foto: "img/will_smith.jpg" },
  { nombre: "Johnny Depp", foto: "img/johnny_depp.jpg" },
  { nombre: "Keanu Reeves", foto: "img/keanu_reeves.jpg" },
  { nombre: "Matt Damon", foto: "img/matt_damon.jpg" },
  { nombre: "Christian Bale", foto: "img/christian_bale.jpg" },
  { nombre: "Tom Hanks", foto: "img/tom_hanks.jpg" },
  { nombre: "Hugh Jackman", foto: "img/hugh_jackman.jpg" },
  { nombre: "Ryan Reynolds", foto: "img/ryan_reynolds.jpg" },
  { nombre: "Chris Hemsworth", foto: "img/chris_hemsworth.jpg" },
  { nombre: "Chris Evans", foto: "img/chris_evans.jpg" },
  { nombre: "Mark Ruffalo", foto: "img/mark_ruffalo.jpg" },
  { nombre: "Robert Downey Jr.", foto: "img/robert_downey_jr.jpg" },
  { nombre: "Scarlett Johansson", foto: "img/scarlett_johansson.jpg" },
  { nombre: "Natalie Portman", foto: "img/natalie_portman.jpg" },
  { nombre: "Emma Stone", foto: "img/emma_stone.jpg" },
  { nombre: "Jennifer Lawrence", foto: "img/jennifer_lawrence.jpg" },
  { nombre: "Margot Robbie", foto: "img/margot_robbie.jpg" },
  { nombre: "Zendaya", foto: "img/zendaya.jpg" },
  { nombre: "Anne Hathaway", foto: "img/anne_hathaway.jpg" },
  { nombre: "Julia Roberts", foto: "img/julia_roberts.jpg" },
  { nombre: "Angelina Jolie", foto: "img/angelina_jolie.jpg" },
  { nombre: "Sandra Bullock", foto: "img/sandra_bullock.jpg" },
  { nombre: "Nicole Kidman", foto: "img/nicole_kidman.jpg" },
  { nombre: "Emma Watson", foto: "img/emma_watson.jpg" },
  { nombre: "Samuel L. Jackson", foto: "img/samuel_l_jackson.jpg" },
  { nombre: "Vin Diesel", foto: "img/vin_diesel.jpg" },
  { nombre: "The Rock", foto: "img/dwayne_johnson.jpg" },
  { nombre: "Guillermo Francella", foto: "img/guillermo_francella.jpg" },
  { nombre: "Ricardo Darín", foto: "img/ricardo_darin.jpg" },
  { nombre: "Miley Cyrus", foto: "img/miley.jpg" },
  { nombre: "Edinson Cavani", foto: "img/edinson_cavani.jpg" },
  { nombre: "Darwin Núñez", foto: "img/darwin_nunez.jpg" },
  { nombre: "Sebastián Coates", foto: "img/sebastian_coates.jpg" },
  { nombre: "Martín Cáceres", foto: "img/martin_caceres.jpg" },
  { nombre: "Diego Godín", foto: "img/diego_godin.jpg" },
  { nombre: "Óscar Tabárez", foto: "img/oscar_tabarez.jpg" },
  { nombre: "Álvaro Recoba", foto: "img/alvaro_recoba.jpg" },
  { nombre: "Rubén Sosa", foto: "img/ruben_sosa.jpg" },
  { nombre: "Enzo Francescoli", foto: "img/enzo_francescoli.jpg" },
  { nombre: "Lucas Torreira", foto: "img/lucas_torreira.jpg" },
  { nombre: "Jonathan Rodríguez", foto: "img/jonathan_rodriguez.jpg" },
  { nombre: "Agustín Canobbio", foto: "img/agustin_canobbio.jpg" },
  { nombre: "Brian Rodríguez", foto: "img/brian_rodriguez.jpg" },
  { nombre: "Brian Ocampo", foto: "img/braianocampo.jpg" },
  { nombre: "Jorge Drexler", foto: "img/jorge_drexler.jpg" },
  { nombre: "Matias Valdez", foto: "img/matiasvaldez.jpg" },
  { nombre: "Flavio Perchman", foto: "img/perchman.jpg" },
  { nombre: "Yao Cabrera", foto: "img/yao.jpg" },
  { nombre: "Cacho de la Cruz", foto: "img/cacho_de_la_cruz.jpg" },
  { nombre: "Omar Gutiérrez", foto: "img/omar_gutierrez.jpg" },
  { nombre: "El Bananero", foto: "img/el_bananero.jpg" },
  { nombre: "Alberto Sonsol", foto: "img/alberto_sonsol.jpg" },
  { nombre: "Martín Kesman", foto: "img/martin_kesman.jpg" },
  { nombre: "Sergio Gorzy", foto: "img/sergio_gorzy.jpg" },
  { nombre: "Bambino Pons ", foto: "img/bambino.jpg" },
  { nombre: "Martin Charquero", foto: "img/charquero.jpg" },
  { nombre: "Rodrigo Romano", foto: "img/rodrigo_romano.jpg" },
  { nombre: "Juan Carlos Scelza", foto: "img/scelza.jpg" },
  { nombre: "Ignacio Álvarez", foto: "img/ignacio_alvarez.jpg" },
  { nombre: "Denis Elías", foto: "img/denis_elias.jpg" },
  { nombre: "Nico Furtado", foto: "img/nico_furtado.jpg" },
  { nombre: "Pepe Guerra", foto: "img/pepe_guerra.jpg" },
  { nombre: "Lucía Topolansky", foto: "img/lucia_topolansky.jpg" },
  { nombre: "José Mujica", foto: "img/jose_mujica.jpg" },
  { nombre: "Adolf Hitler", foto: "img/adolf_hitler.jpg" },
  { nombre: "Iósif Stalin", foto: "img/iosif_stalin.jpg" },
  { nombre: "Luis Lacalle Pou", foto: "img/luis_lacalle_pou.jpg" },
  { nombre: "Julio María Sanguinetti", foto: "img/julio_maria_sanguinetti.jpg" },  
  { nombre: "Joe Biden", foto: "img/joe_biden.jpg" },
  { nombre: "Donald Trump", foto: "img/donald_trump.jpg" },
  { nombre: "Barack Obama", foto: "img/barack_obama.jpg" },
  { nombre: "Hillary Clinton", foto: "img/hillary_clinton.jpg" },
  { nombre: "Bill Clinton", foto: "img/bill_clinton.jpg" },
  { nombre: "George W. Bush", foto: "img/george_bush.jpg" },
  { nombre: "Ronald Reagan", foto: "img/ronald_reagan.jpg" },
  { nombre: "John F. Kennedy", foto: "img/john_kennedy.jpg" },
  { nombre: "Kamala Harris", foto: "img/kamala_harris.jpg" },
  { nombre: "Michelle Obama", foto: "img/michelle_obama.jpg" },
  { nombre: "Vladimir Putin", foto: "img/vladimir_putin.jpg" },
  { nombre: "Kim Jong-un", foto: "img/kim_jong_un.jpg" },
  { nombre: "Nicolás Maduro", foto: "img/nicolas_maduro.jpg" },
  { nombre: "Javier Milei", foto: "img/javier_milei.jpg" },
  { nombre: "José Batlle y Ordóñez", foto: "img/josebatlle.jpg" },
  { nombre: "Wilson Ferreira Aldunate", foto: "img/wilsonferreira.jpg" },
  { nombre: "Tabaré Vázquez", foto: "img/tabare_vazquez.jpg" },
  { nombre: "Juan María Bordaberry", foto: "img/juliomariabordaberry.jpg" },
  { nombre: "Ibai Llanos", foto: "img/ibai.jpg" },
  { nombre: "AuronPlay", foto: "img/auronplay.jpg" },
  { nombre: "El Rubius", foto: "img/el_rubius.jpg" },
  { nombre: "TheGrefg", foto: "img/thegrefg.jpg" },
  { nombre: "Vegetta777", foto: "img/vegetta777.jpg" },
  { nombre: "Willyrex", foto: "img/willyrex.jpg" },
  { nombre: "DjMaRiiO", foto: "img/djmario.jpg" },
  { nombre: "Coscu", foto: "img/coscu.jpg" },
  { nombre: "SantiCAP", foto: "img/santicap.jpg" },
  { nombre: "Tussi Warriors", foto: "img/tussi.jpg" },
  { nombre: "Peke 77", foto: "img/peke.jpg" },
  { nombre: "Lea Sosa", foto: "img/leasosa.jpg" },
  { nombre: "Johnny Te Cuento", foto: "img/johnny-te-cuento.jpg" },
  { nombre: "GuilleFutbol", foto: "img/guillefutbol.jpg" },
  { nombre: "Javo Machado", foto: "img/javomachado.jpg" },
  { nombre: "Vale Sulca", foto: "img/valesulca.jpg" },
  { nombre: "Dross", foto: "img/dross.jpg" },
  { nombre: "Luisito Comunica", foto: "img/luisito_comunica.jpg" },
  { nombre: "Fernanfloo", foto: "img/fernanfloo.jpg" },
  { nombre: "MrBeast", foto: "img/mrbeast.jpg" },
  { nombre: "IShowSpeed", foto: "img/ishowspeed.jpg" },
  { nombre: "Spreen", foto: "img/spreen.jpg" },
  { nombre: "Homero Simpson", foto: "img/homero_simpson.jpg" },
  { nombre: "Marge Simpson", foto: "img/marge_simpson.jpg" },
  { nombre: "Bart Simpson", foto: "img/bart_simpson.jpg" },
  { nombre: "Lisa Simpson", foto: "img/lisa_simpson.jpg" },
  { nombre: "Maggie Simpson", foto: "img/maggie_simpson.jpg" },
  { nombre: "Bob Esponja", foto: "img/bob_esponja.jpg" },
  { nombre: "Patricio", foto: "img/patricio_estrella.jpg" },
  { nombre: "Calamardo", foto: "img/calamardo.jpg" },
  { nombre: "Goku", foto: "img/goku.jpg" },
  { nombre: "Vegeta", foto: "img/vegeta.jpg" },
  { nombre: "Piccolo", foto: "img/piccolo.jpg" },
  { nombre: "Gohan", foto: "img/gohan.jpg" },
  { nombre: "Freezer", foto: "img/freezer.jpg" },
  { nombre: "Naruto", foto: "img/naruto.jpg" },
  { nombre: "Sasuke", foto: "img/sasuke.jpg" },
  { nombre: "Mickey Mouse", foto: "img/mickey_mouse.jpg" },
  { nombre: "Minnie Mouse", foto: "img/minnie_mouse.jpg" },
  { nombre: "Pato Donald", foto: "img/pato_donald.jpg" },
  { nombre: "Pluto", foto: "img/pluto.jpg" },
  { nombre: "Shrek", foto: "img/shrek.jpg" },
  { nombre: "Burro", foto: "img/burro.jpg" },
  { nombre: "Fiona", foto: "img/fiona.jpg" },
  { nombre: "Buzz Lightyear", foto: "img/buzz_lightyear.jpg" },
  { nombre: "Woody", foto: "img/woody.jpg" },
  { nombre: "Iron Man", foto: "img/iron_man.jpg" },
  { nombre: "Capitán América", foto: "img/capitan_america.jpg" },
  { nombre: "Thor", foto: "img/thor.jpg" },
  { nombre: "Hulk", foto: "img/hulk.jpg" },
  { nombre: "Spider-Man", foto: "img/spiderman.jpg" },
  { nombre: "Batman", foto: "img/batman.jpg" },
  { nombre: "Superman", foto: "img/superman.jpg" },
  { nombre: "Joker", foto: "img/joker.jpg" },
  { nombre: "Harley Quinn", foto: "img/harley_quinn.jpg" },
  { nombre: "Darth Vader", foto: "img/darth_vader.jpg" },
  { nombre: "Yoda", foto: "img/yoda.jpg" },
  { nombre: "Chewbacca", foto: "img/chewbacca.jpg" },
  { nombre: "Harry Potter", foto: "img/harry_potter.jpg" },
  { nombre: "Hermione Granger", foto: "img/hermione.jpg" },
  { nombre: "Lilo", foto: "img/lilo.jpg" },
  { nombre: "Stitch", foto: "img/stitch.jpg" },
  { nombre: "Chimuelo", foto: "img/chimuelo.jpg" },
  { nombre: "Ted", foto: "img/ted.jpg" },
  { nombre: "Mario", foto: "img/mario.jpg" },
  { nombre: "Luigi", foto: "img/luigi.jpg" },
  { nombre: "La Sirenita", foto: "img/sirenita.jpg" },
  { nombre: "Emilia Mernes", foto: "img/emilia.jpg" },
  { nombre: "DeadPool", foto: "img/deadpool.jpg" },
  { nombre: "Mike Wazowski", foto: "img/mikewazowski.jpg" },
  { nombre: "Venom", foto: "img/venom.jpg" },
  { nombre: "Walter White", foto: "img/walter.jpg" },
  { nombre: "Kick Buttowski", foto: "img/kick.jpg" },
  { nombre: "Tom", foto: "img/tom.jpg" },
  { nombre: "Jerry", foto: "img/jerry.jpg" },
  { nombre: "Scooby Doo", foto: "img/scooby.jpg" },
  { nombre: "Pikachu", foto: "img/pikachu.jpg" },
  { nombre: "Sonic", foto: "img/sonic.jpg" },
  { nombre: "Pedro Picapiedra", foto: "img/pedropica.jpg" },
  { nombre: "Goofy", foto: "img/goofy.jpg" },
  { nombre: "Popeye", foto: "img/popeye.jpg" },
  { nombre: "Garfield", foto: "img/garfield.jpg" },
  { nombre: "La Pantera Rosa", foto: "img/lapantera.jpg" },
  { nombre: "Yanina Latorre", foto: "img/yanina.jpg" },
  { nombre: "Wanda Nara", foto: "img/wanda_nara.jpg" },
  { nombre: "Marcelo Tinelli", foto: "img/marcelo_tinelli.jpg" },
  { nombre: "Mirtha Legrand", foto: "img/mirtha_legrand.jpg" },
  { nombre: "Susana Giménez", foto: "img/susana_gimenez.jpg" },
  { nombre: "Carmen Barbieri", foto: "img/carmen_barbieri.jpg" },
  { nombre: "Graciela Alfano", foto: "img/graciela_alfano.jpg" },
  { nombre: "Pampita", foto: "img/pampita.jpg" },
  { nombre: "Nico Occhiato", foto: "img/nicoocchiato.jpg" },
  { nombre: "Florencia Peña", foto: "img/florencia_pena.jpg" },
  { nombre: "Adrián Suar", foto: "img/adrian_suar.jpg" },
  { nombre: "Marley", foto: "img/marley.jpg" },
  { nombre: "Nacho Elizalde", foto: "img/nachoelizalde.jpg" },
  { nombre: "Jorge Rial", foto: "img/jorge_rial.jpg" },
  { nombre: "Ángel De Brito", foto: "img/angel_de_brito.jpg" },
  { nombre: "Homero Pettinato", foto: "img/homeropettinato.jpg" },
  { nombre: "Moria Casán", foto: "img/moria_casan.jpg" },
  { nombre: "Miguel Granados", foto: "img/miguegranados.jpg" },
  { nombre: "Flor Jazmín", foto: "img/florjazmin.jpg" },
  { nombre: "Lizy Tagliani", foto: "img/lizytagliani.jpg" },
  { nombre: "Tomas Mazza", foto: "img/tomasmazza.jpg" },
  { nombre: "Martin Cirio", foto: "img/martincirio.jpg" },
  { nombre: "Moski", foto: "img/moski.jpg" },
  { nombre: "Gaspi", foto: "img/gaspi.jpg" },
  { nombre: "Luquitas Rodriguez", foto: "img/luquitas.jpg" },
  { nombre: "Nacho Ruglio", foto: "img/ruglio.jpg" },
  { nombre: "Flavio Azzaro", foto: "img/azzaro.jpg" },
  { nombre: "Maxi de la Cruz", foto: "img/maxidelacruz.jpg" },
  { nombre: "Tiago PZK", foto: "img/tiagopzk.jpg" },  
  { nombre: "Bad Gyal", foto: "img/BadGyal.jpg" },
  { nombre: "Young Miko", foto: "img/youngmiko.jpg" },
  { nombre: "China Zorrilla", foto: "img/china_zorrilla.jpg" },
  { nombre: "Eduardo Galeano", foto: "img/eduardo_galeano.jpg" },
  { nombre: "Mario Benedetti", foto: "img/mario_benedetti.jpg" },
  { nombre: "Hugo Burel", foto: "img/hugo_burel.jpg" },
  { nombre: "Tabaré Cardozo", foto: "img/tabare_cardozo.jpg" },
  { nombre: "Cacho Castaña (UY)", foto: "img/cacho_castana.jpg" },
  { nombre: "Alvaro Navia", foto: "img/alvaro_navia.jpg" },
  { nombre: "Petru Valensky", foto: "img/petru_valensky.jpg" },
  { nombre: "Cecilia Bonino", foto: "img/cecilia_bonino.jpg" },
  { nombre: "Kairo Herrera", foto: "img/kairo_herrera.jpg" },
  { nombre: "María Noel Riccetto", foto: "img/maria_noel_riccetto.jpg" },
  { nombre: "Daniel Viglietti", foto: "img/daniel_viglietti.jpg" },
  { nombre: "Alfredo Zitarrosa", foto: "img/zitarrosa.jpg" },
  { nombre: "Los Fatales (Fabián Delgado)", foto: "img/losfatales.jpg" },
  { nombre: "Jeremia Recoba", foto: "img/recoba_jr.jpg" },
  { nombre: "Andrés Cunha", foto: "img/andres_cunha.jpg" },
  { nombre: "Esteban Ostojich", foto: "img/esteban_ostojich.jpg" },
  { nombre: "Sebastián Giovanelli", foto: "img/giovanelli.jpg" },
  { nombre: "Federico Buysan", foto: "img/buysan.jpg" },
  { nombre: "Shawn Mendes", foto: "img/shawn_mendes.jpg" },
  { nombre: "Post Malone", foto: "img/post_malone.jpg" },
  { nombre: "Travis Scott", foto: "img/travis_scott.jpg" },
  { nombre: "Kendrick Lamar", foto: "img/kendrick_lamar.jpg" },
  { nombre: "Drake", foto: "img/drake.jpg" },
  { nombre: "Taylor Swift", foto: "img/taylor_swift.jpg" },
  { nombre: "Jay-Z", foto: "img/jay_z.jpg" },
  { nombre: "Kanye West", foto: "img/kanye_west.jpg" },
  { nombre: "Snoop Dogg", foto: "img/snoop_dogg.jpg" },
  { nombre: "Eminem", foto: "img/eminem.jpg" },
  { nombre: "50 Cent", foto: "img/50cent.jpg" },
  { nombre: "Doja Cat", foto: "img/doja_cat.jpg" },
  { nombre: "Rosalía", foto: "img/rosalia.jpg" },
  { nombre: "Anuel AA", foto: "img/anuel.jpg" },
  { nombre: "Sech", foto: "img/sech.jpg" },
  { nombre: "Arcangel", foto: "img/arcangel.jpg" },
  { nombre: "Wisin", foto: "img/wisin.jpg" },
  { nombre: "Yandel", foto: "img/yandel.jpg" },
  { nombre: "Prince Royce", foto: "img/prince_royce.jpg" },
  { nombre: "Romeo Santos", foto: "img/romeo_santos.jpg" },
  { nombre: "Chespirito", foto: "img/chespirito.jpg" },
  { nombre: "El Chavo del 8", foto: "img/chavo.jpg" },
  { nombre: "Quico", foto: "img/quico.jpg" },
  { nombre: "La Chilindrina", foto: "img/chilindrina.jpg" },
  { nombre: "Doña Florinda", foto: "img/dona_florinda.jpg" },
  { nombre: "Don Ramón", foto: "img/don_ramon.jpg" },
  { nombre: "Profesor Jirafales", foto: "img/jirafales.jpg" },
  { nombre: "El Chapulín Colorado", foto: "img/chapulin.jpg" },
  { nombre: "Cantinflas", foto: "img/cantinflas.jpg" },
  { nombre: "Tin Tin", foto: "img/tintin.jpg" },
  { nombre: "Diego Simeone", foto: "img/simeone.jpg" },
  { nombre: "José Mourinho", foto: "img/mourinho.jpg" },
  { nombre: "Pep Guardiola", foto: "img/guardiola.jpg" },
  { nombre: "Carlo Ancelotti", foto: "img/ancelotti.jpg" },
  { nombre: "Zinedine Zidane", foto: "img/zidane.jpg" },
  { nombre: "Andrés Calamaro", foto: "img/calamaro.jpg" },
  { nombre: "Residente", foto: "img/residente.jpg" },
  { nombre: "Kurt Cobain", foto: "img/kurt_cobain.jpg" },
  { nombre: "Elvis Presley", foto: "img/elvis.jpg" },
  { nombre: "Michael Jackson", foto: "img/michael_jackson.jpg" },
  { nombre: "Whitney Houston", foto: "img/whitney.jpg" },
  { nombre: "Madonna", foto: "img/madonna.jpg" },
  { nombre: "Britney Spears", foto: "img/britney.jpg" },
  { nombre: "Christina Aguilera", foto: "img/christina_aguilera.jpg" },
  { nombre: "Katy Perry", foto: "img/katy_perry.jpg" },
  { nombre: "Jennifer Lopez", foto: "img/jlo.jpg" },
  { nombre: "Beyoncé", foto: "img/beyonce.jpg" },
  { nombre: "Adele", foto: "img/adele.jpg" },
  { nombre: "Enrique Iglesias", foto: "img/enrique_iglesias.jpg" },
  { nombre: "Gonzalo Bergessio", foto: "img/gonzalo_bergessio.jpg" },
  { nombre: "Freddie Mercury", foto: "img/freddie_mercury.jpg" },
  { nombre: "Nicolas Lodeiro", foto: "img/nico_lodeiro.jpg" },
  { nombre: "Luis Artime", foto: "img/luis_artime.jpg" },
  { nombre: "Héctor Scarone", foto: "img/scarone.jpg" },
  { nombre: "Atilio García", foto: "img/atilio_garcia.jpg" },
  { nombre: "Felipe Carballo", foto: "img/felipe_carballo.jpg" },
  { nombre: "Matías Viña", foto: "img/matias_vina.jpg" },
  { nombre: "Felipe Carvalho", foto: "img/felipe_carvalho.jpg" },
  { nombre: "Guillermo Cotugno", foto: "img/guillermo_cotugno.jpg" },
  { nombre: "Ignacio Lores", foto: "img/ignacio_lores.jpg" },
  { nombre: "Franco Fagúndez", foto: "img/franco_fagundez.jpg" },
  { nombre: "Facundo Machado", foto: "img/facundo_machado.jpg" },
  { nombre: "Yonatan Rodríguez", foto: "img/yonatan_rodriguez.jpg" },
  { nombre: "Christian Oliva", foto: "img/christian_oliva.jpg" },
  { nombre: "Sergio Rochet", foto: "img/sergio_rochet.jpg" },
  { nombre: "Emiliano Velázquez", foto: "img/emiliano_velazquez.jpg" },
  { nombre: "Gabriel Báez", foto: "img/gabriel_baez.jpg" },
  { nombre: "Paolo Calione", foto: "img/paolo_calione.jpg" },
  { nombre: "Lucas Villalba", foto: "img/lucas_villalba.jpg" },
  { nombre: "Exequiel Mereles", foto: "img/exequiel_mereles.jpg" },
  { nombre: "Bruno Arady", foto: "img/bruno_arady.jpg" },
  { nombre: "Brayan Cortés", foto: "img/brayan_cortes.jpg" },
  { nombre: "Gastón Silva", foto: "img/gaston_silva.jpg" },
  { nombre: "Damián Suárez", foto: "img/damian_suarez.jpg" },
  { nombre: "Emanuel Gularte", foto: "img/emanuel_gularte.jpg" },
  { nombre: "Maximiliano Olivera", foto: "img/maximiliano_olivera.jpg" },
  { nombre: "Léo Coelho", foto: "img/leo_coelho.jpg" },
  { nombre: "Pedro Milans", foto: "img/pedro_milans.jpg" },
  { nombre: "Ignacio Sosa", foto: "img/ignacio_sosa.jpg" },
  { nombre: "Leonardo Fernández", foto: "img/leonardo_fernandez.jpg" },
  { nombre: "Eduardo Darias", foto: "img/eduardo_darias.jpg" },
  { nombre: "Jesús Trindade", foto: "img/jesus_trindade.jpg" },
  { nombre: "Eric Remedi", foto: "img/eric_remedi.jpg" },
  { nombre: "David Terans", foto: "img/david_terans.jpg" },
  { nombre: "Javier Cabrera", foto: "img/javier_cabrera.jpg" },
  { nombre: "Héctor Villalba", foto: "img/hector_villalba.jpg" },
  { nombre: "Maximiliano Silvera", foto: "img/maximiliano_silvera.jpg" },
  { nombre: "Matías Arezo", foto: "img/matias_arezo.jpg" },
  { nombre: "Fernando Morena", foto: "img/fernando_morena.jpg" },
  { nombre: "Obdulio Varela", foto: "img/obdulio_varela.jpg" },
  { nombre: "Abraham Simpson", foto: "img/abraham.jpg" },
{ nombre: "Ned Flanders", foto: "img/flanders.jpg" },
{ nombre: "Milhouse Van Houten", foto: "img/milhouse.jpg" },
{ nombre: "Nelson Muntz", foto: "img/nelson.jpg" },
{ nombre: "Moe Szyslak", foto: "img/moe.jpg" },
{ nombre: "Barney Gómez", foto: "img/barney.jpg" },
{ nombre: "Apu Nahasapeemapetilon", foto: "img/apu.jpg" },
{ nombre: "Mr. Burns", foto: "img/burns.jpg" },
{ nombre: "Smithers", foto: "img/smithers.jpg" },
{ nombre: "Krusty el Payaso", foto: "img/krusty.jpg" },
{ nombre: "Bob Patiño", foto: "img/bobpatino.jpg" },
{ nombre: "Kylie Jenner", foto: "img/kylie.jpg" },
{ nombre: "Kim Kardashian", foto: "img/kimkar.jpg" },
{ nombre: "Gustaf", foto: "img/gustaf.jpg" },
{ nombre: "Davo Xeneize", foto: "img/davo.jpg" },
{ nombre: "La Cobra", foto: "img/lacobra.jpg" },
{ nombre: "Ronaldo Nazario", foto: "img/ronaldo.jpg" },
{ nombre: "Harry Styles", foto: "img/harrys.jpg" },
{ nombre: "Tom Holland", foto: "img/tomholland.jpg" },
{ nombre: "Pedro Pascal", foto: "img/pedropascal.jpg" },
{ nombre: "Alessandro Del Piero", foto: "img/delpiero.jpg" },
{ nombre: "Andrea Pirlo", foto: "img/pirlo.jpg" },
{ nombre: "Ángel Correa", foto: "img/correa.jpg" },
{ nombre: "Arjen Robben", foto: "img/robben.jpg" },
{ nombre: "Ashley Cole", foto: "img/ashleycole.jpg" },
{ nombre: "Blaise Matuidi", foto: "img/matuidi.jpg" },
{ nombre: "Cesc Fàbregas", foto: "img/fabregas.jpg" },
{ nombre: "Dani Alves", foto: "img/danialves.jpg" },
{ nombre: "David Beckham", foto: "img/beckham.jpg" },
{ nombre: "David Silva", foto: "img/silva.jpg" },
{ nombre: "Diego Costa", foto: "img/diegocosta.jpg" },
{ nombre: "Edin Džeko", foto: "img/dzeko.jpg" },
{ nombre: "Fernando Torres", foto: "img/torres.jpg" },
{ nombre: "Franck Ribéry", foto: "img/ribery.jpg" },
{ nombre: "Gareth Bale", foto: "img/bale.jpg" },
{ nombre: "Gerard Moreno", foto: "img/gerardmoreno.jpg" },
{ nombre: "Gianluigi Donnarumma", foto: "img/donnarumma.jpg" },
{ nombre: "Giorgio Chiellini", foto: "img/chiellini.jpg" },
{ nombre: "Guti", foto: "img/guti.jpg" },
{ nombre: "Iago Aspas", foto: "img/aspas.jpg" },
{ nombre: "James Rodríguez", foto: "img/james.jpg" },
{ nombre: "Javier Hernández", foto: "img/chicharito.jpg" },
{ nombre: "João Félix", foto: "img/joaofelix.jpg" },
{ nombre: "Juan Mata", foto: "img/mata.jpg" },
{ nombre: "Karim Benzema", foto: "img/benzema.jpg" },
{ nombre: "Kevin-Prince Boateng", foto: "img/boateng.jpg" },
{ nombre: "Luka Jović", foto: "img/jovic.jpg" },
{ nombre: "Marcelo Brozović", foto: "img/brozovic.jpg" },
{ nombre: "Marco Reus", foto: "img/reus.jpg" },
{ nombre: "Mario Götze", foto: "img/gotze.jpg" },
{ nombre: "Mario Mandžukić", foto: "img/mandzukic.jpg" },
{ nombre: "Mats Hummels", foto: "img/hummels.jpg" },
{ nombre: "Memphis Depay", foto: "img/depay.jpg" },
{ nombre: "Michy Batshuayi", foto: "img/batshuayi.jpg" },
{ nombre: "Raheem Sterling", foto: "img/sterling.jpg" },
{ nombre: "Raúl González", foto: "img/raul.jpg" },
{ nombre: "Robert Pires", foto: "img/pires.jpg" },
{ nombre: "Romelu Lukaku", foto: "img/lukaku.jpg" },
{ nombre: "Samuel Eto’o", foto: "img/etoo.jpg" },
{ nombre: "José María Listorti", foto: "img/jose_maria_listorti.jpg" },
{ nombre: "Aníbal Pachano", foto: "img/anibal_pachano.jpg" },
{ nombre: "Jey Mammón", foto: "img/jey_mammon.jpg" },
{ nombre: "Noelia Marzol", foto: "img/noelia_marzol.jpg" },
{ nombre: "Nati Jota", foto: "img/nati_jota.jpg" },
{ nombre: "Gaston Edul", foto: "img/gaston_edul.jpg" },
{ nombre: "Nicolás Vázquez", foto: "img/nico_vazquez.jpg" },
{ nombre: "Gimena Accardi", foto: "img/gime_accardi.jpg" },
{ nombre: "La China Suárez", foto: "img/china_suarez.jpg" },
{ nombre: "Franco Mastantuono", foto: "img/franco_mastantuono.jpg" },
{ nombre: "Jude Bellingham", foto: "img/jude_bellingham.jpg" },
{ nombre: "Vinícius Júnior", foto: "img/vinicius_junior.jpg" },
{ nombre: "Lamine Yamal", foto: "img/lamine_yamal.jpg" },
{ nombre: "Pedri", foto: "img/pedri.jpg" },
{ nombre: "Jamal Musiala", foto: "img/jamal_musiala.jpg" },
{ nombre: "Florian Wirtz", foto: "img/florian_wirtz.jpg" },
{ nombre: "Bukayo Saka", foto: "img/bukayo_saka.jpg" },
{ nombre: "Phil Foden", foto: "img/phil_foden.jpg" },
{ nombre: "Declan Rice", foto: "img/declan_rice.jpg" },
{ nombre: "Trent Alexander-Arnold", foto: "img/trent_alexander_arnold.jpg" },
{ nombre: "Marcus Rashford", foto: "img/marcus_rashford.jpg" },
{ nombre: "Mason Mount", foto: "img/mason_mount.jpg" },
{ nombre: "Kai Havertz", foto: "img/kai_havertz.jpg" },
{ nombre: "Joshua Kimmich", foto: "img/joshua_kimmich.jpg" },
{ nombre: "Leon Goretzka", foto: "img/leon_goretzka.jpg" },
{ nombre: "Alphonso Davies", foto: "img/alphonso_davies.jpg" },
{ nombre: "Theo Hernández", foto: "img/theo_hernandez.jpg" },
{ nombre: "Rafael Leão", foto: "img/rafael_leao.jpg" },
{ nombre: "Khvicha Kvaratskhelia", foto: "img/khvicha_kvaratskhelia.jpg" },
{ nombre: "Lautaro Martínez", foto: "img/lautaro_martinez.jpg" },
{ nombre: "Joško Gvardiol", foto: "img/josko_gvardiol.jpg" },
{ nombre: "Achraf Hakimi", foto: "img/achraf_hakimi.jpg" },
{ nombre: "Heung-min Son", foto: "img/son_heung_min.jpg" },
{ nombre: "Bruno Fernandes", foto: "img/bruno_fernandes.jpg" },
{ nombre: "Casemiro", foto: "img/casemiro.jpg" },
{ nombre: "Antony", foto: "img/antony.jpg" },
{ nombre: "Richarlison", foto: "img/richarlison.jpg" },
{ nombre: "Álisson Becker", foto: "img/alisson_becker.jpg" },
{ nombre: "Thibaut Courtois", foto: "img/thibaut_courtois.jpg" },
{ nombre: "Jan Oblak", foto: "img/jan_oblak.jpg" },
{ nombre: "Raphaël Varane", foto: "img/raphael_varane.jpg" },
{ nombre: "Antonio Rüdiger", foto: "img/antonio_rudiger.jpg" },
{ nombre: "Áymeric Laporte", foto: "img/aymeric_laporte.jpg" },
{ nombre: "João Cancelo", foto: "img/joao_cancelo.jpg" },
{ nombre: "Bernardo Silva", foto: "img/bernardo_silva.jpg" },
{ nombre: "Riyad Mahrez", foto: "img/riyad_mahrez.jpg" },
{ nombre: "Martin Ødegaard", foto: "img/martin_odegaard.jpg" },
{ nombre: "Christian Pulisic", foto: "img/christian_pulisic.jpg" },
{ nombre: "Xavi Simons", foto: "img/xavi_simons.jpg" },
{ nombre: "Federico Chiesa", foto: "img/federico_chiesa.jpg" },
{ nombre: "Ragnar Lothbrok", foto: "img/ragnar_lothbrok.jpg" },
{ nombre: "Lagertha", foto: "img/lagertha.jpg" },
{ nombre: "Floki", foto: "img/floki.jpg" },
{ nombre: "Bjorn Ironside", foto: "img/bjorn_ironside.jpg" },
{ nombre: "Ivar el Deshuesado", foto: "img/ivar.jpg" },
{ nombre: "Tommy Shelby", foto: "img/tommy_shelby.jpg" },
{ nombre: "Arthur Shelby", foto: "img/arthur_shelby.jpg" },
{ nombre: "Alfie Solomons", foto: "img/alfie_solomons.jpg" },
{ nombre: "Michael Gray", foto: "img/michael_gray.jpg" },
{ nombre: "Polly Gray", foto: "img/polly_gray.jpg" },
{ nombre: "Walter White Jr.", foto: "img/walter_white_jr.jpg" },
{ nombre: "Jesse Pinkman", foto: "img/jesse_pinkman.jpg" },
{ nombre: "Saul Goodman", foto: "img/saul_goodman.jpg" },
{ nombre: "Gus Fring", foto: "img/gus_fring.jpg" },
{ nombre: "Mike Ehrmantraut", foto: "img/mike_ehrmantraut.jpg" },
{ nombre: "Tony Soprano", foto: "img/tony_soprano.jpg" },
{ nombre: "Paulie Gualtieri", foto: "img/paulie_gualtieri.jpg" },
{ nombre: "Omar Little", foto: "img/omar_little.jpg" },
{ nombre: "Rick Grimes", foto: "img/rick_grimes.jpg" },
{ nombre: "Daryl Dixon", foto: "img/daryl_dixon.jpg" },
{ nombre: "Negan", foto: "img/negan.jpg" },
{ nombre: "Glenn Rhee", foto: "img/glenn_rhee.jpg" },
{ nombre: "Shane Walsh", foto: "img/shane_walsh.jpg" },
{ nombre: "Yamandú Orsi", foto: "img/yamandu.jpg" },
{ nombre: "Chayanne", foto: "img/chayanne.jpg" },
{ nombre: "Marco Antonio Solís", foto: "img/marco_antonio_solis.jpg" },
{ nombre: "Lola Índigo", foto: "img/lola_indigo.jpg" },
{ nombre: "Aitana", foto: "img/aitana.jpg" },
{ nombre: "Manuel Turizo", foto: "img/manuel_turizo.jpg" },
{ nombre: "Martin Maneiro", foto: "img/martinmaneiro.jpg" },
{ nombre: "Agustin Mayero", foto: "img/agusmayero.jpg" },
{ nombre: "Jeremias Sosa", foto: "img/jeresosa.jpg" },
{ nombre: "Nico Collazo", foto: "img/nicocollazo.jpg" },
{ nombre: "Ezequiel Perdomo", foto: "img/ezeperdomo.jpg" },
{ nombre: "Lucia Maneiro", foto: "img/lulimaneiro.jpg" },
{ nombre: "Facundo Camacho", foto: "img/pacheque.jpg" },
{ nombre: "Resta", foto: "img/resta.jpg" },
{ nombre: "Maravilla", foto: "img/pacheque.jpg" },
{ nombre: "Monango", foto: "img/monango.jpg" },
{ nombre: "Matias Perdomo", foto: "img/matiperdomo.jpg" },
{ nombre: "Evelin Perdomo", foto: "img/eveperdomo.jpg" },
{ nombre: "Nahuel Cornejo", foto: "img/nahucornejo.jpg" },
{ nombre: "Emiliano Zecchini", foto: "img/emizecchini.jpg" },
{ nombre: "Andres Maneiro", foto: "img/manso.jpg" },
{ nombre: "Javier Cornejo", foto: "img/javiercornejo.jpg" },
{ nombre: "Andrea Maneiro", foto: "img/andrea.jpg" },
{ nombre: "Yessi Mayero", foto: "img/yessi.jpg" },
{ nombre: "Paola Mayero", foto: "img/paomayero.jpg" },
{ nombre: "Natalia Mayero", foto: "img/natimayero.jpg" },
{ nombre: "Nicolas Mayero", foto: "img/nicomayero.jpg" },
{ nombre: "Daniel Mayero", foto: "img/danielmayero.jpg" },
{ nombre: "Marcela Cabaña", foto: "img/marcelacabaña.jpg" },
{ nombre: "Teresita Maneiro", foto: "img/tiatere.jpg" },
{ nombre: "Damian Maneiro", foto: "img/damimaneiro.jpg" },
{ nombre: " ", foto: "img/nicomayero.jpg" },
{ nombre: "Nicolas Mayero", foto: "img/nicomayero.jpg" },
{ nombre: "Nicolas Mayero", foto: "img/nicomayero.jpg" },
];
window.famosos = famosos;