  const famososPorTematica = {
  todos: famosos.map(f => f.nombre),
  
  Uruguay: ["Agustín Canobbio", "Agustín Casanova", "Alberto Sonsol", "Alfonso Espino", "Alfredo Zitarrosa", 
"Alvaro Navia", "Andrés Cunha", "Atilio García", "Álvaro Recoba", "Brian Rodríguez", 
"Bruno Arady", "Cacho Castaña (UY)", "Cacho de la Cruz", "Cecilia Bonino", 
"Chacho Ramos", "China Zorrilla", "Christian Oliva", "Damián Suárez", 
"Daniel Viglietti", "Darwin Núñez", "David Terans", "Denis Elías", "Diego Forlán", 
"Diego Godín", "Diego Lugano", "Eduardo Darias", "Eduardo Galeano", "Edinson Cavani", 
"El Bananero", "El Zaraza", "Emanuel Gularte", "Emiliano Velázquez", "Enzo Francescoli", 
"Esteban Ostojich", "Exequiel Mereles", "Facundo Machado", "Facundo Pellistri", "Federico Buysan", 
"Fede Valverde", "Felipe Carballo", "Felipe Carvalho", "Fernando Morena", "Fernando Muslera", 
"Flavio Perchman", "Franco Fagúndez", "Gastón Silva", "Gonzalo Carneiro", 
"Gonzalo Petit","Gustaf", "GuilleFutbol", "Guillermo Cotugno", "Héctor Scarone", 
"Hugo Burel", "Ignacio Álvarez", "Ignacio Lores", "Ignacio Sosa", 
"Javo Machado", "Javier Cabrera", "Jeremia Recoba", "Jesús Trindade", "Johnny Te Cuento", 
"Jorge Drexler", "José Batlle y Ordóñez", "José Mujica", "Jonathan Rodríguez", "Juan Carlos Scelza", 
"Juan María Bordaberry", "Julio María Sanguinetti", "Kairo Herrera", "Lea Sosa", "Leonardo Fernández", 
"Los Fatales (Fabián Delgado)", "Luana", "Lucas Sugo", "Lucas Torreira", "Lucas Villalba", 
"Lucía Topolansky", "Luciano Boggio", "Luis Artime", "Luis Lacalle Pou", "Luis Suárez", 
"Marcos Da Costa", "Mario Benedetti", "Martín Cáceres", "Martín Charquero", "Martín Kesman", 
"Martín Piña", "María Noel Riccetto", "Matias Valdez", "Matías Arezo", "Matías Viña", 
"Maxi Gómez", "Maxi de la Cruz", "Maximiliano Olivera", "Maximiliano Silvera", "Natalia Oreiro", 
"Nacho Ruglio", "Nico Furtado", "Nico López", "Nicolas Lodeiro", "Nicolás de la Cruz", 
"Obdulio Varela", "Omar Gutiérrez", "Óscar Tabárez", "Paolo Calione", "Pedro Milans", 
"Pepe Guerra", "Peke 77", "Petru Valensky", "Rafa Cotelo", "Raúl Castro (Falta y Resto)", 
"Rodrigo Bentancur", "Rodrigo Romano", "Rubén Sosa", "Ruben Rada", "SantiCAP", 
"Sebastián Abreu", "Sebastián Coates", "Sebastián Giovanelli", "Sergio Gorzy", "Sergio Rochet", 
"Tabaré Cardozo", "Tabaré Vázquez", "The La Planta", "Tussi Warriors", "Vale Sulca", 
"Wilson Ferreira Aldunate", "Yao Cabrera", "Yonatan Rodríguez","Yamandú Orsi",
],
  Futbol: ["Agustín Canobbio", "Alessandro Del Piero", "Alfonso Espino", "Álvaro Recoba", "Ángel Correa", "Ángel Di María", "Andrés Iniesta",
"Antoine Griezmann", "Arjen Robben", "Ashley Cole", "Atilio García", "Blaise Matuidi", "Brayan Cortés", "Brian Ocampo", "Brian Rodríguez",
"Bruno Arady", "Carlo Ancelotti", "Carlos Tévez", "Cesc Fàbregas", "Christian Oliva", "Cole Palmer", "Cristiano Ronaldo", "Damián Suárez",
"Dani Alves", "Darwin Núñez", "David Beckham", "David Silva", "David Terans", "Diego Costa", "Diego Forlán", "Diego Godín", "Diego Lugano",
"Diego Maradona", "Diego Simeone", "Edin Džeko", "Edinson Cavani", "Eduardo Darias", "Eduardo Vargas", "Emanuel Gularte",
"Emiliano Velázquez", "Enzo Francescoli", "Eric Remedi", "Erling Haaland", "Exequiel Mereles", "Facundo Machado", "Facundo Pellistri",
"Fede Valverde", "Felipe Carballo", "Felipe Carvalho", "Fernando Morena", "Fernando Muslera", "Fernando Torres", "Francesco Totti",
"Franco Fagúndez", "Franco Mastantuono", "Franck Ribéry", "Gabriel Báez", "Gabriel Batistuta", "Gareth Bale", "Gastón Silva",
"Gerard Moreno", "Gerard Piqué", "Gianluigi Buffon", "Gianluigi Donnarumma", "Gonzalo Bergessio", "Gonzalo Carneiro", "Gonzalo Petit",
"Guillermo Cotugno", "Guti", "Harry Kane", "Héctor Scarone", "Héctor Villalba", "Iago Aspas", "Ignacio Lores", "Ignacio Sosa",
"Iker Casillas", "Javier Cabrera", "Javier Hernández", "Javier Mascherano", "Jeremia Recoba", "Jesús Trindade", "João Félix",
"Jonathan Rodríguez", "José Mourinho", "Juan Mata", "Juan Román Riquelme", "Karim Benzema", "Keylor Navas", "Kevin De Bruyne",
"Kevin-Prince Boateng", "Kylian Mbappé", "Leonardo Fernández", "Léo Coelho", "Lionel Messi", "Lucas Torreira", "Lucas Villalba",
"Luciano Boggio", "Luis Artime", "Luis Mejía", "Luis Suárez", "Luka Jović", "Luka Modrić", "Manuel Neuer", "Marcelo",
"Marcelo Brozović", "Martín Cáceres", "Martín Palermo", "Matías Arezo", "Matías Viña", "Maxi Gómez", "Maximiliano Olivera",
"Maximiliano Silvera", "Mauro Icardi", "Memphis Depay", "Michy Batshuayi", "Mohamed Salah", "Neymar Jr.", "Nico López",
"Nicolas Lodeiro", "Nicolás de la Cruz", "Obdulio Varela", "Paolo Calione", "Paulo Dybala", "Paulo Ferreira", "Pedro Milans",
"Pelé", "Pep Guardiola", "Raheem Sterling", "Raúl González", "Robert Lewandowski", "Robert Pires", "Rodrigo Bentancur",
"Ronaldinho", "Ronaldo Nazario", "Romelu Lukaku", "Rubén Sosa", "Samuel Eto’o", "Sebastián Abreu", "Sebastián Coates",
"Sergio Agüero", "Sergio Ramos", "Sergio Rochet", "Toni Kroos", "Virgil van Dijk", "Yonatan Rodríguez", "Zinedine Zidane",
"Jude Bellingham", "Vinícius Júnior", "Lamine Yamal", "Pedri", "Jamal Musiala", 
"Florian Wirtz", "Bukayo Saka", "Phil Foden", "Declan Rice", "Trent Alexander-Arnold",
"Marcus Rashford", "Mason Mount", "Kai Havertz", "Joshua Kimmich", "Leon Goretzka",
"Alphonso Davies", "Theo Hernández", "Rafael Leão", "Khvicha Kvaratskhelia", "Lautaro Martínez",
"Joško Gvardiol", "Achraf Hakimi", "Heung-min Son", "Bruno Fernandes", "Casemiro",
"Antony", "Richarlison", "Álisson Becker", "Thibaut Courtois", "Jan Oblak",
"Raphaël Varane", "Antonio Rüdiger", "Áymeric Laporte", "João Cancelo", "Bernardo Silva",
"Riyad Mahrez", "Martin Ødegaard", "Christian Pulisic", "Xavi Simons", "Federico Chiesa"
],
  Cine: ["Abraham Simpson", "Al Pacino", "Angelina Jolie", "Anne Hathaway", "Apu Nahasapeemapetilon", 
"Barney Gómez", "Bart Simpson", "Batman", "Bob Esponja","Bob Patiño", "Brad Pitt", 
"Burro", "Buzz Lightyear", "Calamardo", "Cantinflas", "Capitán América", 
"Chewbacca", "Chespirito", "Chimuelo", "Chris Evans", "Chris Hemsworth", 
"Christian Bale", "Darth Vader", "DeadPool", "Denzel Washington", "Don Ramón", 
"Doña Florinda", "El Chapulín Colorado", "El Chavo del 8", "Emma Stone", "Emma Watson", 
"Fiona", "Freezer", "Garfield", "Gohan", "Goku", 
"Goofy", "Guillermo Francella", "Harley Quinn", "Harry Potter", "Hermione Granger", 
"Homer Simpson", "Hugh Jackman", "Iron Man", "Jennifer Lawrence", "Jerry", 
"Johnny Depp", "Joker", "Julia Roberts", "Keanu Reeves", "Kick Buttowski", 
"Krusty el Payaso", "La Chilindrina", "La Pantera Rosa", "La Sirenita", "Leonardo DiCaprio", 
"Lilo", "Lisa Simpson", "Luigi", "Maggie Simpson", "Mario", 
"Margot Robbie", "Marge Simpson", "Mark Ruffalo", "Matt Damon", "Mickey Mouse", 
"Mike Wazowski", "Milhouse Van Houten", "Minnie Mouse", "Moe Szyslak", "Morgan Freeman", 
"Mr. Burns", "Naruto", "Natalie Portman", "Ned Flanders", "Nelson Muntz", 
"Nicole Kidman", "Patricio", "Pato Donald", "Pedro Picapiedra", "Piccolo", "Pedro Pascal",
"Pikachu", "Pluto", "Popeye", "Profesor Jirafales", "Quico", 
"Ricardo Darín", "Robert De Niro", "Robert Downey Jr.", "Ryan Reynolds", "Samuel L. Jackson", 
"Sandra Bullock", "Sasuke", "Scarlett Johansson", "Scooby Doo", "Shrek", 
"Smithers", "Sonic", "Spider-Man", "Stitch", "Superman", 
"Ted", "The Rock", "Thor", "Tin Tin", "Tom","Tom Holland", 
"Tom Cruise", "Tom Hanks", "Vegeta", "Venom", "Vin Diesel", 
"Walter White", "Will Smith", "Woody", "Yoda", "Zendaya","Ragnar Lothbrok", "Lagertha", "Floki", "Bjorn Ironside", "Ivar el Deshuesado",
"Tommy Shelby", "Arthur Shelby", "Alfie Solomons", "Michael Gray", "Polly Gray",
"Walter White Jr.", "Jesse Pinkman", "Saul Goodman", "Gus Fring", "Mike Ehrmantraut",
"Tony Soprano", "Paulie Gualtieri", "Omar Little","Rick Grimes", "Daryl Dixon",
"Negan", "Glenn Rhee", "Shane Walsh"
  ],
  Musica: [ "50 Cent", "Aitana", "Adele", "Agustín Casanova", "Ariana Grande", "Anuel AA", "Arcangel", 
"Bad Bunny", "Bad Gyal", "Beyoncé", "Billie Eilish", "Bizarrap", "Bruno Mars", "Britney Spears", 
"Camila Cabello", "Camilo", "Carlos Vives", "Cazzu", "Chacho Ramos", "Charly García", 
"Chayanne", "Christina Aguilera", "Daddy Yankee", "Denis Elías", "Diego Torres", "Doja Cat", 
"Don Omar", "Drake", "Dua Lipa", "Duki", "Ed Sheeran", "Eladio Carrión", "Elvis Presley", 
"Eminem", "Enrique Iglesias", "Farruko", "Feid", "Fito Páez", "Freddie Mercury", "Gustavo Cerati", 
"Harry Styles", "J Balvin", "Jay-Z", "Jennifer Lopez", "Joaquín Sabina", "Jorge Drexler", 
"Juanes", "Kanye West", "Karol G", "Katy Perry", "Kendrick Lamar", "Kurt Cobain", "La Joaqui", 
"Lali Esposito", "Lola Índigo", "Luana", "Lucas Sugo", "Luis Fonsi", "Madonna", "Maluma", 
"Marc Anthony", "Marcos Da Costa","Marco Antonio Solís", "María Becerra", "Martín Piña", "Manuel Turizo", 
"Michael Jackson", "Miley Cyrus", "Myke Towers", "Natalia Oreiro", "Nathy Peluso", "Nicki Nicole", 
"Ozuna", "Paula Rubio", "Paulo Londra", "Peke 77", "Peso Pluma", "Pepe Guerra", "Post Malone", 
"Prince Royce", "Quevedo", "Rauw Alejandro", "Residente", "Ricardo Arjona", "Ricardo Montaner", 
"Ricky Martin", "Romeo Santos", "Rosalía", "Ruben Rada", "Sam Smith", "Sech", "Selena Gomez", 
"Shakira", "Shawn Mendes", "Snoop Dogg", "Sofía Reyes", "Taylor Swift", "The La Planta", 
"The Weeknd", "Tiago PZK", "Tini Stoessel", "Travis Scott", "Tussi Warriors", "Whitney Houston", 
"Wisin", "Yandel", "Young Miko",
],
  Farandula: ["Adrián Suar", "Ángel De Brito", "Aníbal Pachano", "Carmen Barbieri", "Flor Jazmín", 
"Florencia Peña", "Gaspi", "Gaston Edul", "Gimena Accardi", "Graciela Alfano", 
"Homero Pettinato", "Jey Mammón", "Jorge Rial", "José María Listorti", "La China Suárez", 
"Lizzy Tagliani", "Luquitas Rodriguez", "Marcelo Tinelli", "Marley", "Martin Cirio", 
"Maxi de la Cruz", "Miguel Granados", "Mirtha Legrand", "Moria Casán", "Moski", 
"Nacho Elizalde", "Nati Jota", "Nico Occhiato", "Nicolás Vázquez", "Noelia Marzol", 
"Pampita", "Susana Giménez", "Wanda Nara", "Yanina Latorre"
  ],
  Politicos: ["Barack Obama", "Bill Clinton", "Donald Trump", "George W. Bush", "Hillary Clinton", 
"Javier Milei", "Joe Biden", "John F. Kennedy", "José Batlle y Ordóñez", "José Mujica", 
"Juan María Bordaberry", "Julio María Sanguinetti", "Kamala Harris", "Kim Jong-un", "Lucía Topolansky", 
"Luis Lacalle Pou", "Michelle Obama", "Nicolás Maduro", "Ronald Reagan", "Tabaré Vázquez", 
"Vladimir Putin", "Wilson Ferreira Aldunate"
  ],
  Influencers: ["AuronPlay", "Coscu", "Davo Xeneize", "DjMaRiiO", "Dross", "El Rubius", 
"Fernanfloo", "GuilleFutbol", "Ibai Llanos", "IShowSpeed", "Javo Machado", 
"Johnny Te Cuento","Kylie Jenner", "Kim Kardashian","La Cobra","Lea Sosa", "Luisito Comunica", "MrBeast", "Peke 77", 
"SantiCAP", "Spreen", "TheGrefg", "Tussi Warriors", "Vale Sulca", "Tomas Mazza",
"Vegetta777", "Willyrex", "Yao Cabrera"
  ],
  Simpsons: ["Abraham Simpson", "Apu Nahasapeemapetilon", "Barney Gómez", "Bart Simpson","Bob Patiño", "Homero Simpson", 
"Krusty el Payaso", "Lisa Simpson", "Maggie Simpson", "Marge Simpson", "Milhouse Van Houten", 
"Moe Szyslak", "Mr. Burns", "Ned Flanders", "Nelson Muntz", "Smithers"
],
  Conocidos: [“Martin Maneiro”, “Agustin Mayero”, “Jeremias Sosa”, “Nico Collazo”, “Ezequiel Perdomo”, “Lucia Maneiro”, 
    “Facundo Camacho”, “Resta”, “Maravilla”, “Monango”, “Matias Perdomo”, “Evelin Perdomo”, “Nahuel Cornejo”, “Emiliano Zecchini”, 
    “Andres Maneiro”, “Javier Cornejo”, “Andrea Maneiro”, “Yessi Mayero”, “Paola Mayero”, “Natalia Mayero”, “Nicolas Mayero”, 
    “Daniel Mayero”, “Marcela Cabaña”, “Teresita Maneiro”, “Damian Maneiro”]
};
window.famososPorTematica = famososPorTematica;
